#pragma once

#include "LibraryInfo.h"
#include "CompilerSettings.h"
#include <string>
#include <vector>
#include <string_view>

// A named build target (executable or library) within a project.
struct ProjectTarget {

    enum class TARGET_TYPE : int
    {
        TT_EXECUTABLE = 0,
        TT_STATIC_LIB = 1,
        TT_SHARED_LIB = 2
    };

    static constexpr std::string_view TYPE_KEYS[] = {
        "executable",
        "static_library",
        "shared_library"
    };

    constexpr std::string_view to_str(TARGET_TYPE type) {
        switch (type) {
        case TARGET_TYPE::TT_EXECUTABLE: return TYPE_KEYS[0];
        case TARGET_TYPE::TT_STATIC_LIB: return TYPE_KEYS[1];
        case TARGET_TYPE::TT_SHARED_LIB: return TYPE_KEYS[2];
        }
        return "unknown";
    }

    ProjectTarget() = default;
    ProjectTarget(const std::string& name, const std::vector<std::string>& sources);
    explicit ProjectTarget(const std::string& name);


    bool isExecutable() const;
    bool isSharedLibrary() const;
    bool isStaticLibrary() const;

    std::string abbr() const;

public:

    std::string name = "";
    std::string type { to_str(TARGET_TYPE::TT_EXECUTABLE) }; // "executable", "static_library", "shared_library"
    std::vector<std::string> sources {};      // paths relative to project root
    std::vector<std::string> link_targets {}; // names of other ProjectTargets this links against

};

// Build systems gedi can generate a build file for; the index is the radio
// position in the New Project / Project Properties dialogs.
inline constexpr const char* kBuildSystemKeys[]   = {"cmake", "make", "meson", "watcom"};
inline constexpr const char* kBuildSystemLabels[] = {"CMake", "Make", "Meson", "Watcom"};
inline constexpr int         kBuildSystemCount    = 4;

// Radio index of a build-system key (unknown keys map to CMake).
inline int buildSystemIndex(std::string_view key)
{
    for (int i = 0; i < kBuildSystemCount; ++i)
        if (key == kBuildSystemKeys[i]) return i;
    return 0;
}

// Internal project model.  Serialised to/from a .gproj text file whose
// location determines the project root (root is never stored in the file).
struct GediProject {
    int         version      = 1;
    std::string name;
    std::string root;           // absolute path to the project root directory
    std::string build_system = "cmake";   // "cmake", "make", "meson", "watcom" (Open Watcom wmake)
    std::string cpp_standard = "c++17";  // kept for legacy compat; authoritative copy is in compiler_settings

    CompilerSettings compiler_settings;  // build flags applied when gedi drives the build

    std::vector<std::string> sources;   // paths relative to root (legacy; used for migration)
    std::vector<ProjectTarget> targets; // named build targets
    std::vector<LibraryInfo> libraries;

    // Imported projects (see MakefileImporter): the build file already exists
    // and is maintained by the user.  gedi builds with it but never rewrites it.
    std::string build_file;                    // relative to root; empty = generated by gedi
    std::string make_tool;                     // "wmake" for Open Watcom makefiles; empty = GNU make
    std::vector<std::string> aux_build_files;  // included / sub-directory makefiles, relative to root
    std::vector<std::string> include_dirs;     // -I directories, relative to root (code intelligence)
    std::vector<std::string> defines;          // -D definitions (code intelligence)

    bool hasExternalBuildFile() const { return !build_file.empty(); }

    // Built with Open Watcom's wmake: an imported Watcom makefile, or a
    // project gedi generates a Watcom makefile for.
    bool usesWmake() const { return make_tool == "wmake" || build_system == "watcom"; }

    // -I/-D flags (absolute include paths) for libclang, from include_dirs/defines.
    std::string codeModelFlags() const;

    // Returns the canonical file path: <root>/<name>.gproj
    std::string projectFilePath() const;

    // Save to the canonical file path.
    bool save() const;

    // Load from an explicit file path.  On success, populates `out` and
    // sets out.root to the directory that contains the file.
    static bool load(const std::string& path, GediProject& out);

    // gets the build file name from the project type
    std::string buildFile() const;

    std::string buildFilePath() const;

    bool removeFileFromBuildSystem(const std::string& file_to_remove, const std::string &rel);

    bool removeFileFromCMakeLists(const std::string& cmake_path, const std::string& rel_path);

    bool removeFileFromMakefile(const std::string& project_root, const std::string& rel_path);

    bool removeFileFromMesonBuild(const std::string& project_root, const std::string& rel_path);

    bool addFileToMakefile(const std::string& project_root, const std::string& rel_path);

    bool addFileToMesonBuild(const std::string& project_root, const std::string& rel_path);

    bool addFileToCMakeLists(const std::string& cmake_path, const std::string& new_file);
};
